### PR TITLE
Test running after build using xvfb

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

No need to bump the build number as this doesn't actually change anything.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by gartung** [comment]
Maybe try
xvfb-run -a cmsShow.exe --soft --help

**Comment by chrisburr** [comment]
Thanks for figuring out how to fix this 👍

**Comment by gartung** [comment]
You're welcome. CMS is working on an official fwlite repo instead of my personally maintained copy.

**Pull request merged**
